### ISSUE TITLE
单词导出

### ISSUE THREAD

**Issue by xizhedong** [baotlake/deep-reading#18]
你好，这是不错的项目，我非常喜欢。
能不能增加一个单词导出功能，这样可以到导入词典app,进行复习回顾。或者在单词表添加一个隐藏释义的功能，这样也能复习回顾

**Comment by baotlake** [comment]
是的，目前单词相关的功能的确还很简陋，有待进一步完善。导出单词功能应该会比较简单，我确认下你需要导出什么格式的呢，是`.txt`格式，然后每行一个单词这样吗？

**Comment by xizhedong** [comment]
对的，就是你描述的那样，是.txt格式，然后每行一个单词，你可以尝试导入有道词典试一试

**Comment by xizhedong** [comment]
有一个金山词霸手机端的导入词典api
https://module4app.iciba.com/
这网址只能手机打开，大佬可以试一试

**Comment by xizhedong** [comment]
大佬最近在忙吗？跪求更新

**Comment by baotlake** [comment]
已更新，单词页面顶部标题旁边有个下载按钮，点击即可下载导出的txt文件

**Comment by baotlake** [comment]
已更新，单词页面顶部标题旁边有个下载按钮，点击即可下载导出的txt文件

**Comment by xizhedong** [comment]
真不错，感谢大佬
