### ISSUE TITLE
浏览器插件翻译句子时显示不全

### ISSUE THREAD

**Issue by Forgo7ten** [BaotLake/deep-reading#8]
![Screenshot_2022-01-01-16-54-19-049_com kiwibrowse](https://user-images.githubusercontent.com/57509907/147847359-9fa1204d-2593-4a3b-91d7-5f03f193fa2d.jpg)
浏览器：Kiwibrowse
系统：MIUI12.5.7
翻译句子时会有部分在界面外、显示不全

**Comment by BaotLake** [comment]
我试了下，在这个域名下确实有这个问题（不过滚动一下就又好了），我会去找找问题的

**Comment by BaotLake** [comment]
插件0.1.0发布啦，这个问题已经修复。

发布链接：
https://github.com/BaotLake/deep-reading/releases/tag/ext_0.0.1
